### ISSUE TITLE
Can't seam to make it work correctly with navigation controller

### ISSUE THREAD

**Issue by AntonijoDev** [lkzhao/ElasticTransition#10]
Hi,
I have a project in which I use navigation controller and transition like "option" transition in your ezample project is not animating correctly. For example when I start the example project and tap on option button, the new controller slides from the bottom, and the parent controller slides upwards and dimes a bit so that the content of the parent controller is still visible. like in the picture: 
![simulator screen shot 16 feb 2016 12 05 34](https://cloud.githubusercontent.com/assets/9429000/13074575/a0447f8a-d4a5-11e5-9de8-3163d1cfb108.png)

As picture shows we can see the content of parent view controller it says: "navigation controller" in dimmed red letters and this is perfect, this is what I want. But when I add the navigation controller to the project and I add the following line as instructed in the manual:

`self.navigationController?.delegate = transition`

, no mater in which project the example one or in my project, this behaviour changes. It changes in a way that the content of a parent controller hides after cca. 1/2 of a second, and it reveals again when I try to scroll out the new controller:

![simulator screen shot 16 feb 2016 12 12 56](https://cloud.githubusercontent.com/assets/9429000/13074710/a250024e-d4a6-11e5-81b8-e64c16ca2bd4.png)

Can you please help me to achieve the same result with project that use navigation controller?
Thx in advance...

PS. for second screenshot I had to change the segue to "present modally", cause with "show segue" the parent controller was all white.

**Comment by lkzhao** [comment]
Navigation controller only transitions from one view controller to another view controller. It doesn't layout one VC on top of another. That is why the background view controller is removed from the screen once the next view controller is presented. It is an optimization done by Apple and no way to work around that. If you use navigationController, then you shouldn't override contentLength and let the view controller take up the whole screen. The effect you want to achieve is suppose to be a modal presentation(one on top of another VC). If you don't mind me asking, why do you want to do it with a navigation controller? I will just present a modal inside a navigation controller to achieve that effect.

**Comment by mitchellporter** [comment]
> I will just present a modal inside a navigation controller to achieve that effect.

This is the correct way to do it. Just hacked it together myself. Maybe we should add an example of this to the example project?

**Comment by AntonijoDev** [comment]
I think you misunderstood me. I am not trying to do a push, I am trying to present it modally but the only difference from your example is that the VC1 on which I am trying to present another (VC2) is embedded in navigation controller. So there is no pushing on navigation stack, the segue in storyboard is defined as modal and the result I get is that the VC2 shows and takes contentLength of VC1 but VC1 disappears, so there is no blurred transparency on top of remaining visible part of VC1 like you have in your example. 
I tried to resolve it by creating container view  on VC1 and then apply your example on the containers embedded VC (VC3), and still no blurred transparency, the VC3 again disappears. Do you have any suggestions? It seams that show segue when is applied on a VC that is not part of navigation does something that can't be replicated by any of other segues Apple provides with VCs that are a part of navigation. Maybe some kind of custom segue?

**Comment by mitchellporter** [comment]
@AntonijoDev If you could link us to an example project that we can download and run that would help a lot.

**Comment by AntonijoDev** [comment]
I have modified your example and you can find it here:
https://github.com/AntonijoDev/TestTransition.git

Run "Option" mode from menu...

The only thing new is that first VC is embeded in navigationviewcontroller and the option segue is now defined as modal. When you start the example you will see that the animation runs well but there is a glitch at the end and the original VC (the firs one that should be visible above the option vc) disappears.

**Comment by lkzhao** [comment]
in InitialViewController.swift -> line 85
you have the `modalPresentationStyle` set to `Popover`, change it to `Custom` seems to work

```
vc.modalPresentationStyle = .Custom
```

**Comment by AntonijoDev** [comment]
:), This is unbelievable, it works, i don't know why but it does... Thank you very much.
