### ISSUE TITLE
Invalid redeclaration

### ISSUE THREAD

**Issue by paneaktae** [lkzhao/ElasticTransition#11]
How to fix it? thx .
![screen shot 2559-02-24 at 9 36 49 am](https://cloud.githubusercontent.com/assets/11417557/13273984/2775f9cc-dada-11e5-8c38-39811079df56.png)

**Comment by lkzhao** [comment]
Are you doing cocoapod install or manual install?

**Comment by lkzhao** [comment]
No response. closing.
