### ISSUE TITLE
viewWillAppear on disappearing ViewController is being called accidentally with UIViewController

### ISSUE THREAD

**Issue by thanhn08** [lkzhao/ElasticTransition#13]
Hello,

When using UIViewController by setting the delegate to ElasticTransition, I noticed that viewWillAppear of the old ViewController is being called again right after viewWillDisappear of that same ViewController.

For example, ViewController-A pushes to ViewController-B, the viewWillDisappear will be called on A, then viewWillAppear will be called on A (this should not be called). This may leads to many unexpected problems for some projects that have some logic bound to viewWillAppear.

**Comment by lkzhao** [comment]
This will be fixed in the next release probably 2 weeks from now. It will be great if you can submit a PR to correct this. Otherwise, stay tuned.

**Comment by lkzhao** [comment]
@thanhn08 Please check out 2.2.0 and see if it is fixed. Thank you for reporting this bug.
