### ISSUE TITLE
Strange bug when swiping quickly

### ISSUE THREAD

**Issue by mitchellporter** [lkzhao/ElasticTransition#15]
I have a project where I have a `UINavigationController` and it's root controller. I have setup a modal segue from the nav controller to another controller in my `Storyboard`. I have attached the pan gesture to the nav controller's `UINavigationBar`. When the user swipes down on the nav bar, it triggers the modal segue that I setup on the storyboard, and the user can fully control the transition. This all works perfectly.

However, If I swipe very fast, about 1 out of 10 times something very strange happens. Here's a screenshot: 
<img width="696" alt="screen shot 2016-03-07 at 1 44 59 pm" src="https://cloud.githubusercontent.com/assets/7875419/13584338/f0514f92-e46a-11e5-9942-37b74430c5d5.png">

The main white view is where everything should be, but as you can see all of the other views are located up at the top and are not visible on screen at all. The top views have a `y value of -667`, which is the height in points of the iPhone 6 I am testing on.

I need to fix this. For some reason when the user does a fast swipe all of this happens and then they basically get stuck with a blank screen.

**Comment by lkzhao** [comment]
May I ask for more context here. Is the content of the root view controller being shifted up? Can you do me a favor and try a different transformType and see if it works? Also can you try the 2.0.2 version just to make sure it wasn't the MotionAnimation changes that caused this. Let me know. I do plan to work on this project and clean up bugs like this. But that's probably not going to happen very soon.

**Comment by mitchellporter** [comment]
@lkzhao After several days I finally figured out what is causing this. This happens when you swipe before the system has been told that the previous swipe / transition has finished.

I gave up on this library and created a much simpler interactive transition from scratch, but I started experiencing the same thing. I was able to fix this by utilizing the following functions:

```
UIApplication.sharedApplication().beginIgnoringInteractionEvents()
UIApplication.sharedApplication().endIgnoringInteractionEvents()
```

However, my interactive transition reacts to the pan events differently than this lib, so I still haven't been able to fix this when using ElasticTransition. I just hopped in the code and tried to fix it real quick, but it's still happening and I can't take anymore time for this right now but would be happy to help again in the near future.

**Comment by lkzhao** [comment]
@mitchellporter I might have a fix for this. I am thinking that we should not return a transition delegate for the methods in UIViewControllerTransitioningDelegate protocol when the transitioning flag is set to true. I will create a PR for this fix tonight and can you verify if it fixes your problem? No rush though. do it when you have time. 
Thank you very much for reporting this. Sorry about the time you have lost.

**Comment by mitchellporter** [comment]
> I will create a PR for this fix tonight and can you verify if it fixes your problem?

I would be more than happy to test this. Please keep me updated and let me know when you create the PR, I'll test it right away.

> Thank you very much for reporting this. Sorry about the time you have lost.

Not a problem at all and don't worry, sure I lost some time but I learned a lot along the way and I really can't complain... this is an amazing transition that would have taken me even more time to make from scratch on my own. Your work is greatly appreciated.

**Comment by lkzhao** [comment]
@mitchellporter I have it up on the branch [2.1.1](https://github.com/lkzhao/ElasticTransition/tree/2.1.1)

**Comment by lkzhao** [comment]
Please checkout v2.2.0 and see if it is fixed. Thanks!

**Comment by mitchellporter** [comment]
@lkzhao Hey Luke sorry for the delay I have a deadline right now so don't have much spare time. Will definitely check this out soon and see if the issue has been fixed.

**Comment by A1exandre** [comment]
Hi guys, 

I have a very simple implementation of EslasticTransistion on a view I present from my app main view. 
Swiping really fast on the view does block any kind of touch events and the user ends up stucked on the Elasticview.
