### ISSUE TITLE
transition becomes super slow in the new version 

### ISSUE THREAD

**Issue by Jackson0111** [lkzhao/ElasticTransition#19]
I've been using ElasticTransition for a while. I love it! But I just did a pod update, and the new updated code made my transition super slow. I thought it was something wrong with my own code, but it is super slow too when I ran the new code from the repo. Any idea what's going on?

**Comment by frangeris** [comment]
Same issue here using `2.2.0`, I thought it was me, so I downgrade to another version `2.0.1` and everything works fine, @lkzhao Any idea what's going on with this new version?

Thank you...

**Comment by JPROFFICIAL** [comment]
I :arrow_up: this, I was experiencing the same thing. Updated and now is working fine. Thanks guys!

**Comment by misuqian** [comment]
I think it's that version 2.0.1 not contain MotionAnimation

**Comment by lkzhao** [comment]
Sorry guys, please set the `stiffness` attribute on the transition to ~0.6. I forgot to update the defaultValue.

**Comment by lkzhao** [comment]
Basically that attribute sets the animation speed.
I will update this in the next release
