### ISSUE TITLE
Support NavigationController

### ISSUE THREAD

**Issue by mshll** [lkzhao/ElasticTransition#25]
Does it support transitioning between views inside a navigation bar ?

**Comment by lkzhao** [comment]
It is not supported anymore with the newest version. Use version [2.2.0](https://github.com/lkzhao/ElasticTransition/archive/2.2.0.zip)

```
use_frameworks!
pod "ElasticTransition", "~> 2.2.0"
```

And use like follow:

```
navigationController?.delegate =transition
```

**Comment by iiMshl** [comment]
![screen shot 2016-06-04 at 9 33 55 pm](https://cloud.githubusercontent.com/assets/17913113/15801403/125961a2-2a9c-11e6-8f46-1e7c4baf94d3.png)

**Comment by xinnai** [comment]
I want to use pod "ElasticTransition", "~> 2.2.0" to make navigation work ,but do you have a swift4 version.?
