### ISSUE TITLE
ElasticModalViewController "not open" error

### ISSUE THREAD

**Issue by joelmbell** [lkzhao/ElasticTransition#39]
When trying to subclass ElasticModalViewController in my project I get the error:

 "Cannot inherit from non-open class 'ElasticModalViewController' outside of its defining module.

This happens because I've pulled in ElasticTransition with cocoa pods and its in a different module.

**Comment by 0x7061** [comment]
Please update the Podfile! Either merge to swift3 or change pod branch to master. Thanks!
