### ISSUE TITLE
Obj-C version

### ISSUE THREAD

**Issue by taglia3** [lkzhao/ElasticTransition#4]
It would be interesting to develop an Objective-C version of this awesome transition.

**Comment by lkzhao** [comment]
It is useful to have an Objective-C version. But before doing so, I have to cleanup the API interface and code. Some updates coming soon.

**Comment by taglia3** [comment]
This sounds great! Hope to try the Obj-C version soon ;)

**Comment by magorik** [comment]
Hello! What about Objective-C version? I'm really looking forward to it ,)

**Comment by dexcell** [comment]
This is really cool.
+1 for objective C version

**Comment by lkzhao** [comment]
@taglia @magorik @dexcell 
Anyone is welling to try implementing it in obj-c? I wish to see it but now I really have no time to port. Unfortunately I will need leave this to someone else.

If anyone start doing so, make sure that you port the 2.0.1 version instead of 2.1+.
It should be a straight forward port. I can help a little bit on the objc project as well.

**Comment by taglia3** [comment]
@lkzhao 
Yes, as soon as I've any time i will try implementing in obj-c. Thanks for the tip.

**Comment by taglia3** [comment]
I've just created the repo for the obj-c version at this [Link](https://github.com/taglia3/ElasticTransition-ObjC).
In the next days I will commit the implementation of the version 2.0.1.

**Comment by taglia3** [comment]
@lkzhao I've ported the code of your control, however I'm unable to get it work. Could you help me?
(At this moment I'm testing only the pan from the left edge of the screen)

**Comment by taglia3** [comment]
@lkzhao 
I've fixed some things and now I've achieved the static effect, but at this moment I'm not able to get it works with a progress animation. As soon as you have any time, take a look at the code, I'm sure that you can fix it in a short time.

**Comment by taglia3** [comment]
@lkzhao 
I've fixed all and now it works perfectly.
Could you add the reference link in your repo so that the users could also download the ObjC version?
