### ISSUE TITLE
How to present a view controller embed in navigation controller with such animation?

### ISSUE THREAD

**Issue by qky1412** [lkzhao/ElasticTransition#5]

**Comment by lkzhao** [comment]
Currently not possible. working on it. A big update is coming.

**Comment by lkzhao** [comment]
@qky1412 
With 2.0.0, navigation controller transition is now supported. please checkout the new [README](https://github.com/lkzhao/ElasticTransition)

**Comment by qky1412** [comment]
Amazing work, thx!

**Comment by palozinski** [comment]
README has no information about support UINavigationController.
