### ISSUE TITLE
strange behaviour when presenting navigation controller after presenting the options view controller

### ISSUE THREAD

**Issue by qky1412** [lkzhao/ElasticTransition#6]
1.In the demo, after the actions took as described, the default transition disappear. 
2.If I want the navigation view controller to be presented with the elastic transition, it seems that i should use nav.transitionDelegate = transition rather than nav.delegate = transition, but after doing that, something unexpected happened, my UIAlertViewController presented by my app disappear when it is presented, but it can still be interacted, like its view's alpha become 0 to me.

**Comment by lkzhao** [comment]
[This commit fixed it](https://github.com/lkzhao/ElasticTransition/commit/3727df05b24c33d32a5ce0e2c72e668e06308fae)
Sorry, it is my bad. I changed the zPosition of the view while doing the transition and forgot to set it back.

 **nav.transitionDelegate = transition** is the correct way to present the navigation controller.

**Comment by qky1412** [comment]
great!
