### ISSUE TITLE
Is there a way to change the speed when segue is performed?

### ISSUE THREAD

**Issue by Jackson0111** [lkzhao/ElasticTransition#7]
I have many segues, the transitions look great but I think it may be too fast, is there a way to change that?

**Comment by lkzhao** [comment]
Hi, I will be pushing an update soon that changes the animation library from uikitdynamic to something custom. That will give us more control over how the animation is performed. 
Currently, if you look into ElasticTransition.setupdynamics, you will see that two instance of the CustomSnapBehavior are created. I set the frequency to a hardcoded value 2.5. If you modify this value it will change the speed in which the animation is performed

**Comment by Jackson0111** [comment]
Thanks a lot! I've only been doing iOS dev for 4 months, and I'm interested in making animations but I'm not sure where to start. Any suggestions?

**Comment by lkzhao** [comment]
@Jackson0111 
I just updated the repo(v2.1.0). Now there is a stiffness property that you can adjust for animation speed.

Some suggestion for learning how to do animations: UIView.animationWithDuration is most widely used method for iOS. It is based on Core Animation. If you mastered that, you should start looking into facebook's pop library. Pop is another awesome library and very easy to use as well. UIKitDynamic is for physics simulated animations, you can do many cool things with that, but that is too hardcore for most apps. Anyway, welcome to the iOS world!

**Comment by Jackson0111** [comment]
Thank you SO MUCH, I've been spending like 10+ hrs a day learning and making projects, hopefully it all pays off one day.
