### ISSUE TITLE
ElasticTransition cannot find Motion module on ObjC project.

### ISSUE THREAD

**Issue by pabloepi** [lkzhao/ElasticTransition#9]
Hi guys,

I added ElasticTransition and MotionAnimator classes to my ObjC project, Xcode creates the Bridging header as usual, but ElasticTransition.swift cannot find MotionAnimation module.

Any idea?
Tks!

**Comment by lkzhao** [comment]
Hi, sorry I didn't test out the manual installation. I will update the repo soon.

In the mean time, you can either fallback to [v2.0.1](https://github.com/lkzhao/ElasticTransition/releases/tag/2.0.1) or if you just manually installed ElasticTransition and MotionAnimation, you can remove the line `import MotionAnimation` and it should work. You should get a duplicated extension error on CGPoint as well, just remove one of the implementation.

**Comment by pabloepi** [comment]
Luke, tks for the quick response!

v2.0.1 works like a charm! :)
Just added files to my project, accept Xcode suggestion for bridging-header
file creation and that's all!

Cheers!
Pablo.
